/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define LED_TIME_BLINK 300
#define LED_TIME_LONG 1000
#define DEBOUNCE_PERIOD 5

volatile uint32_t Tick = 0; // volatile aby fungovala v ISR i main



void blikac(void){
	 static uint32_t delay;
	 if (Tick > delay + LED_TIME_BLINK) {
		 GPIOA->ODR ^= (1<<4); // inverze LED1
		 delay = Tick;
	 }
}

void tlacitko(void){      // takhle funguje
	static uint16_t debounce = 0xffff;
	static uint32_t delay;

	 if (Tick > delay + DEBOUNCE_PERIOD) {
		 debounce <<= 1;
		 delay = Tick;

		 if(GPIOC->IDR & (1<<1)){ // kontrola zmáčknutí tlačítka S1
			 debounce |= 0x0001;
		 }
		 if(debounce == 0x8000){
			 GPIOB->ODR ^= (1<<0); // resetování LED2
			 //off_time = Tick + LED_TIME_LONG;
		}
	 }
}

int main(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN; // hodiny
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable hodin
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup

	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PC; // select PC0 for EXTI0
	EXTI->IMR |= EXTI_IMR_MR0; // mask
	EXTI->FTSR |= EXTI_FTSR_TR0; // trigger on falling edge
	NVIC_EnableIRQ(EXTI0_1_IRQn); // enable EXTI0_1

	SysTick_Config(8000); // nastavení hodin na periodu 1ms
    /* Loop forever */

	while(1){
		blikac();
		tlacitko();
	}
}

void EXTI0_1_IRQHandler(void)
 {
	 if (EXTI->PR & EXTI_PR_PR0) { // check line 0 has triggered the IT
		 EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
		 GPIOB->ODR ^= (1<<0); // inverze hodnoty portu B, pin 0, tj. LED2
	 }
 }

void SysTick_Handler(void)
 {
 Tick++;
 }


